namespace SOLVEN.Common
{
    public static class Constants
    {
        /// <summary>
        /// The mail address that will receive the emails generated by this program.
        /// </summary>
        public const string MAIL_TO = "solven.smtp@gmail.com";
    }
}
